apiVersion: v1
kind: Secret
metadata:
  name: medixai-secrets
  namespace: medixai
type: Opaque
data:
  # القيم التالية يجب أن تكون مشفرة base64
  POSTGRES_USER: bWVkaXhhaQ==  # medixai
  POSTGRES_PASSWORD: Y2hhbmdlbWU=  # changeme
  REDIS_PASSWORD: Y2hhbmdlbWU=  # changeme
  JWT_SECRET_KEY: c2VjcmV0  # secret
  JWT_REFRESH_SECRET_KEY: cmVmcmVzaHNlY3JldA==  # refreshsecret
  ENCRYPTION_KEY: ZW5jcnlwdGlvbmtleQ==  # encryptionkey
  STRIPE_API_KEY: c2tfdGVzdF8=  # sk_test_
  SENDGRID_API_KEY: U0dfQVBJX0tFWQ==  # SG_API_KEY
  TWILIO_ACCOUNT_SID: QUNfU0lE  # AC_SID
  TWILIO_AUTH_TOKEN: QVVUSF9UT0tFTg==  # AUTH_TOKEN
  GOOGLE_MAPS_API_KEY: R09PR0xFX01BUFNfS0VZ  # GOOGLE_MAPS_KEY
